version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: tee_backend:${TEE_BACKEND_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      TEE_BACKEND_HOST: 0.0.0.0
